src/Toubarefane/SiteBundle/Entity/File.php
<?php

namespace Toubarefane\SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * File
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Toubarefane\SiteBundle\Entity\FileRepository")
 */
class File
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;
   private $files;

  public function upload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif)
    if (null === $this->files) {
      return;
    }

    // On garde le nom original du fichier de l'internaute
    $name = $this->files->getClientOriginalName();

    // On déplace le fichier envoyé dans le répertoire de notre choix
    $this->files->move($this->getUploadRootDir(), $name);

    // On sauvegarde le nom de fichier dans notre attribut $url
    $this->url = $name;

    // On crée également le futur attribut alt de notre balise <img>
    $this->name = $this->getName();
  }

  public function getUploadDir()
  {
    // On retourne le chemin relatif vers l'image pour un navigateur
    return 'uploads/file';
  }

  protected function getUploadRootDir()
  {
    // On retourne le chemin relatif vers l'image pour notre code PHP
    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return File
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return File
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return File
     */
    public function setUrl($url)
    {
        $this->url = $url;
    
        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return File
     */
    public function setType($type)
    {
        $this->type = $type;
    
        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }
       /**
     * Set files
     *
     * @param string $files
     * @return File
     */
    public function setFiles($files)
    {
        $this->files = $files;
    
        return $this;
    }
    /**
     * Get files
     *
     * @return string 
     */
    public function getFiles()
    {
        return $this->files;
    }
}

src/Toubarefane/SiteBundle/Resources/views/Admin/ajouter.html.twig
{# src/Toubarefane/SiteBundle/Resources/views/Site/modifier.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Modifier un article - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}

  <h2>Ajoutr un article</h2>

  {% include "ToubarefaneSiteBundle:Admin:formulaire.html.twig" %}


 
{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/audio.html.twig
{# src/Toubarefane/SiteBundle/Resources/views/Site/modifier.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Modifier un audio - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}

  <h2>Ajoutr un audio</h2>

  {% include "ToubarefaneSiteBundle:Admin:formulaire.html.twig" %}

  <p>
    Vous éditez un article déjà existant,
    ne le changez pas trop pour éviter
    aux membres de ne pas comprendre
    ce qu'il se passe.
  </p>

 
{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/email.txt.twig
{# src/Toubarefane/SiteBundle/Resources/views/Site/email.txt.twig #}

Bonjour {{ pseudo }},

Toute l'équipe du site se joint à moi pour vous souhaiter la bienvenue sur notre site !

Revenez nous voir souvent !

src/Toubarefane/SiteBundle/Resources/views/Admin/flot.html.twig
{# src/Sdz/BlogBundle/Resources/views/Blog/voir.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Tous les photos - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}
 
        
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Line Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-line-chart"></div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Pie Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-pie-chart"></div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Multiple Axes Line Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-line-chart-multi"></div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Moving Line Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-line-chart-moving"></div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Bar Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-bar-chart"></div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Flot Charts Usage
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <p>Flot is a pure JavaScript plotting library for jQuery, with a focus on simple usage, attractive looks, and interactive features. In SB Admin, we are using the most recent version of Flot along with a few plugins to enhance the user experience. The Flot plugins being used are the tooltip plugin for hoverable tooltips, and the resize plugin for fully responsive charts. The documentation for Flot Charts is available on their website, <a target="_blank" href="http://www.flotcharts.org/">http://www.flotcharts.org/</a>.</p>
                            <a target="_blank" class="btn btn-default btn-lg btn-block" href="http://www.flotcharts.org/">View Flot Charts Documentation</a>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
           
{% block javascripts %}
                
                <!-- jQuery Version 1.11.0 -->
    <script src="{{ asset('js/jquery-1.11.0.js')}}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('js/bootstrap.min.js')}}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{ asset('js/plugins/metisMenu/metisMenu.min.js')}}"></script>

    <!-- Flot Charts JavaScript -->
    <script src="{{ asset('js/plugins/flot/excanvas.min.js')}}"></script>
    <script src="{{ asset('js/plugins/flot/jquery.flot.js')}}"></script>
    <script src="{{ asset('js/plugins/flot/jquery.flot.pie.js')}}"></script>
    <script src="{{ asset('js/plugins/flot/jquery.flot.resize.js')}}"></script>
    <script src="{{ asset('js/plugins/flot/jquery.flot.tooltip.min.js')}}"></script>
    <script src="{{ asset('js/plugins/flot/flot-data.js')}}"></script>
    
     <!-- Custom Theme JavaScript -->
    <script src="{{ asset('js/sb-admin-2.js')}}"></script>
     {% endblock %}
   {% endblock %}
   

src/Toubarefane/SiteBundle/Resources/views/Admin/index.html.twig
{# src/Sdz/BlogBundle/Resources/views/Blog/voir.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Lecture d'un article - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}
  <p class=""><strong>Vous étes sur l'interface d'administration.</strong> </p>
  <p class=""><blink>Toute operation de suppression, modification ou d'ajout est directement visible au internautes.</blink> </p>
 <script type="text/javascript" src="{{ asset('js/jquery-1.11.0.js')}}"></script>
    
<script type="text/javascript" src="{{ asset('js/tbr-admin.js')}}"></script>
{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/modifier.html.twig
{# src/Toubarefane/SiteBundle/Resources/views/Site/modifier.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Modifier un article - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}

  <h2>Modifier un article</h2>

  {% include "ToubarefaneSiteBundle:Admin:formulaire.html.twig" %}

  <p>
    Vous éditez un article déjà existant,
    ne le changez pas trop pour éviter
    aux membres de ne pas comprendre
    ce qu'il se passe.
  </p>
  <p>
  <a href="{{ path('toubarefaneadmin_voirtous') }}" type="button" class="btn btn-info">
   <i class="icon-chevron-left"></i>
    Retour à la liste
    </a>
  </p>
{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/morris.html.twig
{# src/Sdz/BlogBundle/Resources/views/Blog/voir.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Tous les photos - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}
 

                <div class="col-lg-12">
                    <h1 class="page-header">Morris.js Charts</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Area Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="morris-area-chart"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Bar Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="morris-bar-chart"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Line Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="morris-line-chart"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Donut Chart Example
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="morris-donut-chart"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Morris.js Usage
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <p>Morris.js is a jQuery based charting plugin created by Olly Smith. In SB Admin, we are using the most recent version of Morris.js which includes the resize function, which makes the charts fully responsive. The documentation for Morris.js is available on their website, <a target="_blank" href="http://www.oesmith.co.uk/morris.js/">http://www.oesmith.co.uk/morris.js/</a>.</p>
                            <a target="_blank" class="btn btn-default btn-lg btn-block" href="http://www.oesmith.co.uk/morris.js/">View Morris.js Documentation</a>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
           
 
{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/review.html.twig
{# src/Sdz/BlogBundle/Resources/views/Blog/voir.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Lecture d'un article - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}
<div class="well">
  <form method="post" {{ form_enctype(form) }}>
<fieldset>
    <legend>Media</legend>
    <div class="form_field">
        {{ form_label(form.images) }}
        {{ form_widget(form.images, { 'full_name': 'kmv_ampbundle_review[images]' ~ '[]' }) }}
        {% if errorMessages is defined %}
            <ul class="error">
            {% for errorMessage in errorMessages %}
                <li>{{ errorMessage }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
   
</fieldset>
<input type="submit" class="btn btn-primary" />
  </form>
</div>
{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/supprimer.html.twig
{# src/Toubarefane/SiteBundle/Resources/views/Site/modifier.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Modifier un article - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}

    <h2>Supprimer un article</h2>

  <p>
    Etes-vous certain de vouloir supprimer l'article "{{ article.titre }}" ?
  </p>

  {# On met l'id de l'article dans la route de l'action du formulaire #}
  <form action="{{ path('toubarefaneadmin_supprimer', {'id': article.id}) }}" method="post">
    <a href="{{ path('toubarefaneadmin_voir', {'id': article.id}) }}" type="button" class="btn btn-info">
      <i class="icon-chevron-left"></i>
      Retour à l'article
    </a>
    <input type="submit" value="Supprimer" class="btn btn-danger" />
    {{ form_rest(form) }}
  </form>

{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/supprimervideo.html.twig
{# src/Toubarefane/SiteBundle/Resources/views/Site/modifier.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Suppprimer une video - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}

    <h2>Supprimer une video</h2>

  <p>
    Etes-vous certain de vouloir supprimer la video "{{ video.name }}" ?
  </p>

  {# On met l'id de l'video dans la route de l'action du formulaire #}
  <form action="{{ path('toubarefaneadmin_supprimervideo', {'id': video.id}) }}" method="post">
    <a href="{{ path('toubarefaneadmin_tousvideo') }}" type="button" class="btn btn-info">
      <i class="icon-chevron-left"></i>
      Retour aux videos
    </a>
    <input type="submit" value="Supprimer" class="btn btn-danger" />
    {{ form_rest(form) }}
  </form>

{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/video.html.twig
{# src/Toubarefane/SiteBundle/Resources/views/Site/modifier.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Modifier un video - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}

  <h2>Ajoutr un video</h2>

  {% include "ToubarefaneSiteBundle:Admin:formulaire.html.twig" %}

  <p>
    Vous éditez un article déjà existant,
    ne le changez pas trop pour éviter
    aux membres de ne pas comprendre
    ce qu'il se passe.
  </p>

 
{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/voir.html.twig
{# src/Sdz/BlogBundle/Resources/views/Blog/voir.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Lecture d'un article - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}

   <div class="col-lg-6 col-md-6 col-xs-12">
                    <div class="panel">
                         <h2>{{ article.titre }}</h2>
                        <div class="panel-heading">
  {# On vérifie qu'une image soit bien associée à l'article #}
                            {% if article.file is not null %}
                            {% if article.file.type=="image" %}
                            <img class="oimg img-responsive" src="{{ asset(article.file.uploadDir ~ '/' ~article.file.url ) }}"  alt="{{ article.file.name }}" />
                            {% elseif article.file.type=="video" %}
                            
                             <video class="oimg img-responsive" src="{{ asset(article.file.uploadDir ~ '/' ~article.file.url ) }}"   controls="controls" type="video/mp4"><p>{{ article.file.name }}</p></video>  
                             {% elseif article.file.type=="youtube" %}
                            {% set clef=article.file.description |slice(38,35)%}
                             {% set url='<iframe width="570" height="400" src="lien?rel=0&amp;autoplay=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>' %}
                              <li class="img-responsive"> {{ url | replace({'lien': clef}) | raw  }}</li>
                              {% else %}
                             <audio class="oimg img-responsive" src="{{ asset(article.file.uploadDir ~ '/' ~article.file.url ) }}"  controls >{{ article.file.name }}</audio>
                             {% endif %}
                             {% endif %}
                       
                           
  
                             <i>Par {{ article.auteur }}, le {{ article.date|date('d/m/Y') }}</i>

                              <div class="well">
                             {{ article.contenu }}
                             </div>
                             <p>
                         <a href="{{ path('toubarefaneadmin_voirtous') }}" type="button" class="btn btn-info">
                         <i class="icon-chevron-left"></i>
                              Retour à la liste
                         </a>
                                 {% if article.file.type=="youtube" %}
                           <a href="{{ path('toubarefaneadmin_modifieryoutube', {'id': article.id}) }}" type="button" class="btn btn-success">
                          <i class="icon-edit"></i>
                            Modifier l'article
                           </a>
                              {% else %}    
                         <a href="{{ path('toubarefaneadmin_modifier', {'id': article.id}) }}" type="button" class="btn btn-success">
                          <i class="icon-edit"></i>
                            Modifier l'article
                           </a>
                                  {% endif %}
                          <a href="{{ path('toubarefaneadmin_supprimer', {'id': article.id}) }}" type="button" class="btn btn-warning">
                          <i class="icon-edit"></i>
                            Supprimer l'article
                           </a>
                          </p>
                           </div>
                    </div>
   </div>

  

{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/voirtous.html.twig
{# src/Sdz/BlogBundle/Resources/views/Blog/voir.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Lecture d'un article - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}
 {% for article in articles | reverse%}
   <div class="col-lg-12 col-md-12">
                    <div class="panel">
                        <div class="panel-heading">
                     {# On vérifie qu'une image soit bien associée à l'article #}
                            {% if article.file is not null %}
                            {% if article.file.type=="image" %}
                            <li class="unstyled"><a href="{{ path('toubarefaneadmin_modifier', {'id': article.id}) }}" type="button" class="btn-sm btn-success">
                             <i class="icon-edit"></i>
                             Modifier l'article
                              </a>
                               <a href="{{ path('toubarefaneadmin_supprimer', {'id': article.id}) }}" type="button" class="btn-sm btn-danger">
                               <i class="icon-trash"></i>
                              Supprimer l'article
                              </a>
                            </li>
                            <img class="gimg img-responsive" src="{{ asset(article.file.uploadDir ~ '/' ~article.file.url ) }}"  alt="{{ article.file.name }}" />
                           {% elseif article.file.type=="video" %}
                            <li class="unstyled"><a href="{{ path('toubarefaneadmin_modifier', {'id': article.id}) }}" type="button" class="btn-sm btn-success">
                             <i class="icon-edit"></i>
                             Modifier l'article
                              </a>
                               <a href="{{ path('toubarefaneadmin_supprimer', {'id': article.id}) }}" type="button" class="btn-sm btn-danger">
                               <i class="icon-trash"></i>
                              Supprimer l'article
                              </a>
                            </li>
                           <video class="gimg img-responsive" src="{{ asset(article.file.uploadDir ~ '/' ~article.file.url ) }}"  controls="controls" type="video/mp4"><p>{{ article.file.name }}</p></video>  
                          {% elseif article.file.type=="youtube" %}
                            <li class="unstyled"><a href="{{ path('toubarefaneadmin_modifieryoutube', {'id': article.id}) }}" type="button" class="btn-sm btn-success">
                             <i class="icon-edit"></i>
                             Modifier l'article
                              </a>
                               <a href="{{ path('toubarefaneadmin_supprimer', {'id': article.id}) }}" type="button" class="btn-sm btn-danger">
                               <i class="icon-trash"></i>
                              Supprimer l'article
                              </a>
                            </li>
                          {% set clef=article.file.description |slice(38,35)%}
                             {% set url='<iframe width="570" height="400" src="lien?rel=0&amp;autoplay=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>' %}
                          <li class="gimg img-responsive"> {{ url | replace({'lien': clef}) | raw  }}</li>
                          {% else %}
                           <li class="unstyled"><a href="{{ path('toubarefaneadmin_modifier', {'id': article.id}) }}" type="button" class="btn-sm btn-success">
                             <i class="icon-edit"></i>
                             Modifier l'article
                              </a>
                               <a href="{{ path('toubarefaneadmin_supprimer', {'id': article.id}) }}" type="button" class="btn-sm btn-danger">
                               <i class="icon-trash"></i>
                              Supprimer l'article
                              </a>
                            </li>
                           
                           
                           <audio class="gimg img-responsive" src="{{ asset(article.file.uploadDir ~ '/' ~article.file.url ) }}"  controls="controls" >{{ article.file.name }}</audio>
                           
                           {% endif %}
                          {% endif %}
                        
                           <title> {{ article.titre }}</title>
  
                            <i>Par {{ article.auteur }}, le {{ article.date|date('d/m/Y') }}</i>

                           <div class="well">
                            {{ article.contenu }}
                           </div>
                          
                         </div>
                    </div>
   </div>
  
{% endfor %}
{% endblock %}

src/Toubarefane/SiteBundle/Resources/views/Admin/voirtousvideo.html.twig
{# src/Sdz/BlogBundle/Resources/views/Blog/voir.html.twig #}

{% extends "ToubarefaneSiteBundle::layoutAdmin.html.twig" %}

{% block title %}
  Tous les videos - {{ parent() }}
{% endblock %}

{% block toubarefanesite_body %}
 
   
  {# On vérifie qu'une video soit bien associée à l'article #}
  
          {% for videos in videos | reverse%}
            {% if videos.category !="accueil" %}
          <div class="col-lg-3 col-md-6">
                    <div class="panel">
                        <div class="panel-heading">
                            <li class="gimg img-responsive"> {{ videos.embeded | raw }}<h1> {{ videos.name}}</h1><p>{{ videos.description}}</p></li>
                            <li class="unstyled"><a href="{{ path('toubarefaneadmin_modifiervideo', {'id': videos.id}) }}" type="button" class="btn-sm btn-success">
                             <i class="icon-edit"></i>
                             Modifier
                              </a>
                               <a href="{{ path('toubarefaneadmin_supprimervideo', {'id': videos.id}) }}" type="button" class="btn-sm btn-danger">
                               <i class="icon-trash"></i>
                              Supprimer
                              </a>
                            </li>
                        </div>
                    </div>
              </div>
           {% endif %} 
         {% endfor %}  
   
{% endblock %}